Vagrant.configure("2") do |config|
        config.vm.box = "centos6.7_box"
        config.vm.network "private_network" , ip: "192.168.33.16"

        config.vm.provider "virtualbox" do |vb|
                vb.memory=2048
            vb.cpus=1
        end
end
